### ISSUE TITLE
Incorrect branch name for contributions

### ISSUE THREAD

**Issue by TheBoxyBear** [nikeee/docfx-action#17]
I have contributions enabled on my site which includes an "Improve this Doc" button to generate custom markdown in the API Documentation.
![image](https://user-images.githubusercontent.com/15822255/202913580-04d45eab-8f7c-4426-9aac-06ddf0fc45c2.png)

When I serve the site locally, such links work to create a new Markdown file, but lead to 404 when accessed from the published site.

Example URL generated when serving locally* `https://github.com/TheBoxyBear/charttools/new/stable/apiSpec/new?filename=ChartTools_GHLChord__ctor.md`
Example URL from the Pages site for the same member* `https://github.com/TheBoxyBear/charttools/new/7001213bd4db628330554d43a33cb5e6d72feb27/apiSpec/new?filename=ChartTools_GHLChord__ctor.md`

*Template text removed to keep links short

The only difference is the usage of an Id in the published site rater than the branch name. Looking in the DocFx build logs of the action reveals it's incorrectly using the Id of the last commit as a branch name, with the Id matching the one found in the URL causing the 404. This message doesn't appear in the logs when building locally.
`[22-11-20 04:12:50.010]Info:[MetadataCommand.ExtractMetadata]For git repo </github/workspace>, using commit id 7001213bd4db628330554d43a33cb5e6d72feb27 as the branch name.`

**Comment by TheBoxyBear** [comment]
Fixed with the NUnit fork.

**Comment by nikeee** [comment]
Maybe this will be fixed in the next major release of this action. This should lift it en par with the Nuit fork.

**Comment by TheBoxyBear** [comment]
Despite the urls being correct, it seems there's not a further issue with GitHub leading to 404, including for other DocFx sites like [Singulink](https://www.singulink.com/Docs/Singulink.IO.FileSystem/index.html) that have since also disabled contributions.
