### ISSUE TITLE
Error: `fatal: could not read Password for 'https://github.com': No such device or address`

### ISSUE THREAD

**Issue by dotMorten** [nikeee/docfx-action#3]
Getting this error while executing:
> fatal: could not read Password for 'https://github.com': No such device or address

I'm guessing it's because I have the "Improve this doc" links generated which generates links back to the repo so people can submit doc improvements:
https://github.com/dotMorten/NmeaParser/blob/2c286083d220dc4d280387b57d962b02a5b5b4e5/docs/docfx.json#L12

Example output failure:
https://github.com/dotMorten/NmeaParser/commit/2c286083d220dc4d280387b57d962b02a5b5b4e5/checks?check_suite_id=411294712

yaml:
https://github.com/dotMorten/NmeaParser/blob/2c286083d220dc4d280387b57d962b02a5b5b4e5/.github/workflows/ghpages.yml#L22-L25

**Comment by dotMorten** [comment]
Oh if I set GH_PAT that the next build step also uses, it works! It might be good to add to the doc?

**Comment by nikeee** [comment]
Actually I didn't know that docfx might use git credentials. I'll take a look at this.

**Comment by dotMorten** [comment]
I was surprised too. Shouldn't need credentials for a public repo
