### ISSUE TITLE
Suggestion: Publish on DockerHub

### ISSUE THREAD

**Issue by SeanKilleen** [nikeee/docfx-action#6]
I've noticed that every time our GitHub Action fires, it pulls from this repo, which builds the container image.

If this image was published to DockerHub, we could reference the container directly in our Action rather than building it each time, dramatically speeding up the process.

Would you be open to publishing this on DockerHub? If not, would you mind if I did so? 

Thanks!

**Comment by nikeee** [comment]
I recently thought of the same. It seems to be necessary since we now install git and dotnet.

**Comment by nikeee** [comment]
I changed the action to use an image that is automatically built from this repository. It should "just work" without any further configuration.

**Comment by SeanKilleen** [comment]
Beautiful, thank you!
